"""
Stamps the firmware version from git before every build.

    Tagged commit, clean tree    v2.0.0
    develop                      v2.0.1-dev+a1b2c3d
    feature/<name>               v2.0.1-feature.<name>+a1b2c3d
    Uncommitted changes          v2.0.1-dev+a1b2c3d.dirty

A release is made by tagging a commit vX.Y.Z. Only a clean build of exactly
that commit gets the plain version; everything else is numbered as the next
patch, with the branch and commit attached so any build can be traced back.

The result goes into include/version_generated.h, which build_info.h includes.
"""

import os
import re
import subprocess

Import("env")

PROJECT_DIR = env.subst("$PROJECT_DIR")
OUTPUT_PATH = os.path.join(PROJECT_DIR, "include", "version_generated.h")


def git(*args):
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=PROJECT_DIR,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def channel_for(branch):
    if branch == "develop":
        return "dev"
    if branch is None or branch == "HEAD":
        return "detached"
    return re.sub(r"[^0-9A-Za-z._-]", ".", branch)


def firmware_version():
    commit = git("rev-parse", "--short", "HEAD")
    if commit is None:
        return "unknown"

    exact = git("describe", "--tags", "--exact-match", "--match", "v[0-9]*")
    dirty = bool(git("status", "--porcelain", "--untracked-files=no"))

    if exact and not dirty:
        return exact

    major, minor, patch = 0, 0, 0
    tag = git("describe", "--tags", "--abbrev=0", "--match", "v[0-9]*")
    match = re.fullmatch(r"v(\d+)\.(\d+)\.(\d+)", tag or "")
    if match:
        major, minor, patch = (int(part) for part in match.groups())

    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    version = "v%d.%d.%d-%s+%s" % (major, minor, patch + 1, channel_for(branch), commit)

    return version + ".dirty" if dirty else version


def write_if_changed(path, text):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as existing:
            if existing.read() == text:
                return

    with open(path, "w", encoding="utf-8") as out:
        out.write(text)


version = firmware_version()

write_if_changed(OUTPUT_PATH,
    "/*\n"
    " * Generated by scripts/version.py before every build. Do not edit or commit.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    'constexpr char FIRMWARE_VERSION[] = "%s";\n' % version)

print("Firmware version:", version)
