#pragma once

#include <Arduino.h>

#include "version_generated.h"

/*
 * Build identity. HARDWARE_VERSION is bumped by hand when the board changes.
 * FIRMWARE_VERSION comes from git, generated by scripts/version.py at build time.
 * BUILD_TIMESTAMP is filled in by the compiler when device_info.cpp is built.
 */

constexpr char HARDWARE_VERSION[] = "v2.0";

constexpr char BUILD_TIMESTAMP[] = __DATE__ " " __TIME__;
